server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_order
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "3Y8i4XpS2a/Z+H9B4E3OaN1g1RkYj/mJz+f9p7k+L8A="
  expiration: 86400000

file:
  upload-path: D:/SpringCode/demo/uploads/
  access-url: http://localhost:8080/files/
